name: Cron Jobs

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
  workflow_dispatch:

jobs:
  sync-subscribers-guild:
    name: Sync Subscribers to Guild
    runs-on: ubuntu-latest
    steps:
      - name: Sync Subscribers to Guild
        run: |
          curl -X GET "https://api.hey.xyz/cron/syncSubscribersToGuild?secret=${{ secrets.SHARED_SECRET }}"

  sync-followers-standing-guild:
    name: Sync Followers Standing Accounts to Guild
    runs-on: ubuntu-latest
    steps:
      - name: Sync Followers Standing Accounts to Guild
        run: |
          curl -X GET "https://api.hey.xyz/cron/syncFollowersStandingToGuild?secret=${{ secrets.SHARED_SECRET }}"

  remove-expired-subscribers:
    name: Remove Expired Pro Subscribers
    runs-on: ubuntu-latest
    steps:
      - name: Remove Expired Pro Subscribers
        run: |
          curl -X GET "https://api.hey.xyz/cron/removeExpiredSubscribers?secret=${{ secrets.SHARED_SECRET }}"
